@startuml

left to right direction

actor "Адміністрація" as admin
actor "Маркетолог" as marketing
actor "Гість" as guest


rectangle "Система управління готелем" {
  rectangle "Адмін панель" {
    usecase "Додавання доступних кімнат" as added_available_rooms
    usecase "Обробка черги" as processing_queue
    usecase "Отримати інформацію о клієнті" as get_user_info
    usecase "Отримати інформацію по бронюванні" as get_book_info

    admin -- added_available_rooms
    admin -- processing_queue
    admin -- get_book_info
    admin -- get_user_info
    marketing -- get_book_info
  }
  usecase "Рерєстрація" as register
  usecase "Забронювати кімнату" as book_room
  usecase "Обрання рівня комфорту" as select_comfort_level
  usecase "Отримати інформацію о бронюванні" as get_user_book_info
  usecase "Обрання доступних кімнат" as select_available_rooms

  guest -> book_room
  book_room ..> select_available_rooms: <<include>>
  guest -> select_comfort_level
  guest -> register
  guest - get_user_book_info
}


@enduml
