@startuml
left to right direction

actor "Адміністрація" as admin
actor "Маркетолог" as marketing
actor "Гість" as guest

actor "Туристи" as act_t
actor "Подородні бізнесмени" as act_t_b
actor "Сім'ї та группи" as act_f_a_g
actor "Відівдувачі подій" as act_e_v
actor "Ділові туристи" as act_b_t
actor "Послугові компанії" as act_s_c

guest <|-- act_b_t 
guest <|-- act_e_v
guest <|-- act_f_a_g
act_s_c --|> guest
act_t_b --|> guest
act_t --|> guest


rectangle "База данних" {
  usecase "Збір іформації" as collect_data
  usecase "Отримання іформації о клієнті" as receive_client_info

  usecase "Доступні кімнати" as available_rooms

  usecase "Черга в обробку" as queue

  admin -up-> available_rooms
  admin -up-> queue
  admin -up-> collect_data
  admin -up-> receive_client_info

  marketing -up-> collect_data
}


rectangle "Система управління готелем" {
  usecase "Вхід" as login
  usecase "Ререєстрація" as register

  usecase "Обрання рівня комфорту" as comfort_level
  usecase "Забронювати кімнату" as book_room

  usecase "Інформація о бронюванні" as book_info

  guest ---> register
  register -|> login
  register ...> collect_data: <<include>>
  receive_client_info ...> login: <<extend>> 

  guest ---> login
  login -|> comfort_level
  comfort_level --|> book_room
  comfort_level <.. available_rooms : <<extend>>
  book_room ...> queue : <<include>>

  book_info <--- guest
  book_info <. queue : <<extend>>

}


@enduml
